version: "3"
services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  nats:
    image: 'nats:2.8.4'
    expose:
      - "4222"
    ports:
      - "4222:4222"
    hostname: nats-server
